### ISSUE TITLE
Runtime error from Pathy's logs

### ISSUE THREAD

**Issue by djdefi** [es-na-battlesnake/snakes#149]
Was reviewing some logs and noticed this:

```
2022/02/24 04:02:59 3418d32c-7192-44f3-bb4a-79fc80600e23 MOVE 216: right
2022/02/24 04:02:59 http: panic serving 10.240.255.56:62437: runtime error: invalid memory address or nil pointer dereference
goroutine 10956 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x636e00, 0x8585f0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
main.getNextDirection({{{0xc000422060, 0x24}, {{0xc000116128, 0x7}, {0xc000116140, 0x7}, {0xf, 0x1, 0x0, {...}, ...}}, ...}, ...}, ...)
	/usr/src/app/snakes/go/pathy-snake/pathing.go:296 +0xe
main.createSnakeMap({{{0xc000422060, 0x24}, {{0xc000116128, 0x7}, {0xc000116140, 0x7}, {0xf, 0x1, 0x0, {...}, ...}}, ...}, ...})
	/usr/src/app/snakes/go/pathy-snake/pathing.go:29 +0x258
main.move({{{0xc000422060, 0x24}, {{0xc000116128, 0x7}, {0xc000116140, 0x7}, {0xf, 0x1, 0x0, {...}, ...}}, ...}, ...})
	/usr/src/app/snakes/go/pathy-snake/logic.go:38 +0x5a
main.HandleMove({0x6cbe90, 0xc000134ee0}, 0xc000316c00)
	/usr/src/app/snakes/go/pathy-snake/main.go:126 +0x15e
net/http.HandlerFunc.ServeHTTP(0x4a9e06, {0x6cbe90, 0xc000134ee0}, 0xc000134ee0)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x6cbe90, 0xc000134ee0}, 0xc000316c00)
	/usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0x6cb350}, {0x6cbe90, 0xc000134ee0}, 0xc000316c00)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc000082320, {0x6ccd00, 0xc000106180})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
2022/02/24 04:02:59 3418d32c-7192-44f3-bb4a-79fc80600e23 MOVE 218: down
```

Not sure if this indicates a bug or edge case.

cc: @bevns

**Comment by bevns** [comment]
This is kind of both a bug and edge case. It usually happens when Pathy can't find a target cell or a path and subsequently a `next move`. In this example it looks like it failed to get the next move in https://github.com/es-na-battlesnake/snakes/blob/c732de6a795448cc8f9c5e1d0b3cd841a08d055e/snakes/go/pathy-snake/pathing.go#L292 and specifically at https://github.com/es-na-battlesnake/snakes/blob/c732de6a795448cc8f9c5e1d0b3cd841a08d055e/snakes/go/pathy-snake/pathing.go#L296

The likely reason is that there was no path to choose from so it it couldn't get the next move. 

Here is the game from that log: https://play.battlesnake.com/g/3418d32c-7192-44f3-bb4a-79fc80600e23/ and here is a screenshot of the turn that resulted in the `runtime error`:

<img width="494" alt="Screen Shot 2022-02-24 at 8 15 10 AM" src="https://user-images.githubusercontent.com/17680929/155563399-21571f9b-31ec-4607-959b-55fdbb4cbfe9.png">

What happened here is that Pathy's head was at `(X: 5, Y: 5)` so we followed this code path: https://github.com/es-na-battlesnake/snakes/blob/c732de6a795448cc8f9c5e1d0b3cd841a08d055e/snakes/go/pathy-snake/pathing.go#L206-L211

All that really does is set the Target Cell to the bottom left corner `(X: 0, Y: 0)` if we are in the center of the board. Then we looked for the available paths to that cell but because the other snake occupied that cell there were no available paths so when we got down to https://github.com/es-na-battlesnake/snakes/blob/c732de6a795448cc8f9c5e1d0b3cd841a08d055e/snakes/go/pathy-snake/pathing.go#L296 there was no path to check against. 

I can not remember why I added the logic that chooses the bottom left corner if we are in the center of the board. There was a reason at one point but it's escaping me right now. We could easily fix this specific case by removing all of: https://github.com/es-na-battlesnake/snakes/blob/c732de6a795448cc8f9c5e1d0b3cd841a08d055e/snakes/go/pathy-snake/pathing.go#L206-L211 That would leave the target cell selection up to what it does all the other moves. i.e. same as if the head was at `(X: 4, Y: 5)`.
